name: Generate Snake Game

on:
  schedule:
    - cron: "0 */12 * * *"  # Chạy 2 lần/ngày
  workflow_dispatch:        # Cho phép chạy thủ công
  push:
    branches:
      - main

jobs:
  build:
    name: Generate Snake Animation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate the snake
        uses: Platane/snk@v3
        with:
          github_user_name: BeeNoANo      # 👉 đổi tên thành username của bạn
          outputs: dist/snake.svg

      - name: Push to the output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
